# download the data!
rule all:
	input:
		"data/hg19_refseq.ser",
		"jannovar_0.25/data/hg19_refseq.ser",
		"jannovar_0.26/data/hg19_refseq.ser"

rule download_jannovar_ser:
	output:
		file="data/hg19_refseq.ser"
	shell:
		"""
		java -jar jannovar-cli-0.21-SNAPSHOT.jar download -d hg19/refseq
		"""

rule download_jannovar_25_ser:
	output:
		file="jannovar_0.25/data/hg19_refseq.ser"
	shell:
		"""
		cd jannovar_0.25
		java -jar jannovar-cli-0.25-SNAPSHOT.jar download -d hg19/refseq
		"""

rule download_jannovar_26_ser:
	output:
		file="jannovar_0.26/data/hg19_refseq.ser"
	shell:
		"""
		cd jannovar_0.26
		java -jar jannovar-cli-0.26-SNAPSHOT.jar download -d hg19/refseq
		"""

