# download the data!


rule all:
	input:
		"ALL.wgs.phase3_shapeit2_mvncall_integrated_v5b.20130502.sites.vcf.gz",
		"ALL.wgs.phase3_shapeit2_mvncall_integrated_v5b.20130502.sites.vcf.gz.tbi",
		"ExAC.r1.sites.vep.vcf.gz",
		"ExAC.r1.sites.vep.vcf.gz.tbi",
		"UK10K_COHORT.20160215.sites.vcf.gz",
		"UK10K_COHORT.20160215.sites.vcf.gz.tbi"


rule download1KG:
	output:
		file="ALL.wgs.phase3_shapeit2_mvncall_integrated_v5b.20130502.sites.vcf.gz",
		index="ALL.wgs.phase3_shapeit2_mvncall_integrated_v5b.20130502.sites.vcf.gz.tbi"
	shell:
		"""
		wget ftp://ftp.1000genomes.ebi.ac.uk/vol1/ftp/release/20130502/{output.file};
		wget ftp://ftp.1000genomes.ebi.ac.uk/vol1/ftp/release/20130502/{output.index};
		"""

rule downloadExAC:
	output:
		file="ExAC.r1.sites.vep.vcf.gz",
		index="ExAC.r1.sites.vep.vcf.gz.tbi"
	shell:
		"""
		wget ftp://ftp.broadinstitute.org/pub/ExAC_release/release1/{output.file};
		wget ftp://ftp.broadinstitute.org/pub/ExAC_release/release1/{output.index};
		"""

rule downloadUK10K:
	output:
		file="UK10K_COHORT.20160215.sites.vcf.gz",
		index="UK10K_COHORT.20160215.sites.vcf.gz.tbi"
	shell:
		"""
		wget ftp://ngs.sanger.ac.uk/production/uk10k/UK10K_COHORT/REL-2012-06-02/{output.file};
		wget ftp://ngs.sanger.ac.uk/production/uk10k/UK10K_COHORT/REL-2012-06-02/{output.index};
		"""
