configfile: "../config.yml"

def allSamples(a,b):
	samples = []
	samples.extend(a)
	samples.extend(b)
	return samples

SINGLE_SAMPLES = config['SINGLE_SAMPLES']
VCF_SAMPLES = config['VCF_SAMPLES']
SAMPLES = allSamples(SINGLE_SAMPLES, VCF_SAMPLES)


rule all:
	input:
		"mutations/JsonsVCF_annotated.vcf.gz",
		"mutations/JsonsVCF_annotated.vcf.gz.tbi",
		expand("vcf_simulation/{sample}.done", sample=SAMPLES),
		expand("json_simulation/CV/{sample}.json", sample=SAMPLES),
		expand("vcf_annotation/{sample}.vcf.gz", sample=VCF_SAMPLES),
		expand("vcf_annotation/{sample}.vcf.gz.tbi", sample=VCF_SAMPLES),
		expand("vcf_annotation/{sample}.annotation.vcf.gz", sample=VCF_SAMPLES),
		expand("vcf_annotation/{sample}.annotation.vcf.gz.tbi", sample=VCF_SAMPLES),
		expand("json_simulation/real/test/{sample}.json", sample=VCF_SAMPLES),
		expand("json_simulation/real/train/{sample}.json", sample=SINGLE_SAMPLES)





rule annotate:
	input:
		vcf="../mVCF/JsonsVCF.vcf.gz",
		db="../jannovar/data/hg19_refseq.ser",
		exac="../data/ExAC.r0.3.sites.vep.vcf.gz",
		uk="../data/UK10K_COHORT.20160215.sites.vcf.gz",
		caddsnv="../data/whole_genome_SNVs.tsv.gz",
		caddindel="../data/InDels.tsv.gz",
		ref="/home/ngsknecht/Resource/hg19/human_g1k_v37.fasta"
	output:
		"mutations/JsonsVCF_annotated.vcf.gz"
	shell:
		"java -jar ../jannovar/jannovar-cli-0.21-SNAPSHOT.jar annotate-vcf -d {input.db} --exac-vcf {input.exac} --uk10k-vcf {input.uk} --tabix {input.caddsnv} {input.caddindel} --tabix-prefix CADD_SNV_ CADD_INDEL_ --ref-fasta {input.ref} -o '{output}' -i '{input.vcf}'"


rule index:
	input:
		"mutations/JsonsVCF_annotated.vcf.gz"
	output:
		"mutations/JsonsVCF_annotated.vcf.gz.tbi"
	shell:
		"module load htslib/1.3.1 && "
		"tabix '{input}'"

def containsVcf(wc):
	import glob
	return glob.glob("vcf_simulation/"+wc.sample+"_*.vcf.gz")
		

	
rule spikein:
	input:
		index="mutations/JsonsVCF_annotated.vcf.gz.tbi",
		vcf="mutations/JsonsVCF_annotated.vcf.gz",
		omim="OMIM/genemap2.txt",
		back="background/{back}/{back}.refSeq105.AF.vcf.gz"
	output:
		touch("vcf_simulation/{sample}.done")
	run:
		if not containsVcf(wildcards):
			shell("java -jar simulator/pedia-simulator-0.0.1-SNAPSHOT.jar spikein -o {input.omim} -out vcf_simulation/ -v {input.back} -m {input.vcf} --sample {wildcards.sample}")


def vcf_file(wc):
	import glob
	return glob.glob("vcf_simulation/"+wc.sample+"_*.vcf.gz")


rule json:
	input:
		simulation="vcf_simulation/{sample}.done",
		vcf=vcf_file,
		omim="OMIM/genemap2.txt",
		json="../json_cases/{sample}.json"
	output:
		"json_simulation/{back}/CV/{sample}.json"
	shell:
		"java -jar simulator/pedia-simulator-0.0.1-SNAPSHOT.jar extendjson -j {input.json} -v {input.vcf} -o {input.omim} -out {output}"


################### REAL VCFS################################

def getRealVCF(wc):
	configfile: "../json_cases/%s.json" % wc.sample
	filename = config['vcf']['original_filename'].replace(" ", "_").replace("(","").replace(")","",1).replace(")","_").replace(",","").replace("..",".")
	return ("../vcf_cases/%s" % filename)

rule bgZipRealVCF:
	input:
		vcf=getRealVCF,
		json="../json_cases/{sample}.json"
	output:
		vcf="vcf_annotation/{sample}.vcf.gz",
		index="vcf_annotation/{sample}.vcf.gz.tbi"
	shell:
		"""
		module load vcflib/v1.0.0-rc1;
		module load htslib/1.3.1;
		cat {input.vcf} | vcfstreamsort |  bgzip -c  > {output.vcf};
		tabix {output.vcf}
		"""
	

rule annotateRealVCF:
	input:
		vcf="vcf_annotation/{sample}.vcf.gz",
		db="../jannovar/data/hg19_refseq.ser",
		exac="../data/ExAC.r0.3.sites.vep.vcf.gz",
		uk="../data/UK10K_COHORT.20160215.sites.vcf.gz",
		caddsnv="../data/whole_genome_SNVs.tsv.gz",
		caddindel="../data/InDels.tsv.gz",
		ref="/home/ngsknecht/Resource/hg19/human_g1k_v37.fasta"
	output:
		"vcf_annotation/{sample}.annotation.vcf.gz"
	shell:
		"""
		java -jar ../jannovar/jannovar-cli-0.21-SNAPSHOT.jar annotate-vcf \
		-d {input.db} --exac-vcf {input.exac} --uk10k-vcf {input.uk} \
		--tabix {input.caddsnv} {input.caddindel} --tabix-prefix CADD_SNV_ CADD_INDEL_ \
		--ref-fasta {input.ref} -o '{output}' -i '{input.vcf}'
		"""


rule indexRealVCF:
	input:
		"vcf_annotation/{sample}.annotation.vcf.gz"
	output:
		"vcf_annotation/{sample}.annotation.vcf.gz.tbi"
	shell:
		"""
		module load htslib/1.3.1;
		tabix '{input}'
		"""


rule jsonRealTestData:
	input:
		simulation="vcf_simulation/{sample}.done",
		vcf=vcf_file,
		omim="OMIM/genemap2.txt",
		json="../json_cases/{sample}.json"
	output:
		"json_simulation/real/test/{sample}.json"
	shell:
		"""
		java -jar simulator/pedia-simulator-0.0.1-SNAPSHOT.jar extendjson \
		-j {input.json} -v {input.vcf} -o {input.omim} -out {output}
		"""

rule jsonRealTrainData:
	input:
		"json_simulation/CV/{sample}.json"
	output:
		"json_simulation/real/train/{sample}.json"
	shell:
		"""
		ln {input} {output}
		"""



