# download the data!


rule all:
	input:
		"InDels.tsv.gz",
		"InDels.tsv.gz.tbi",
		"whole_genome_SNVs.tsv.gz",
		"whole_genome_SNVs.tsv.gz.tbi",
		"cadd_exon_snv.v1.3.tsv.gz",
		"cadd_exon_snv.v1.3.tsv.gz.tbi",
		"cadd_exon_indel.v1.3.tsv.gz",
		"cadd_exon_indel.v1.3.tsv.gz.tbi"

rule download_CADD_indels:
	output:
		file="InDels.tsv.gz",
		index="InDels.tsv.gz.tbi"
	shell:
		"""
		wget http://krishna.gs.washington.edu/download/CADD/v1.3/{output.file};
		wget http://krishna.gs.washington.edu/download/CADD/v1.3/{output.index};
		"""

rule download_CADD_SNVs:
	output:
		file="whole_genome_SNVs.tsv.gz",
		index="whole_genome_SNVs.tsv.gz.tbi"
	shell:
		"""
		wget http://krishna.gs.washington.edu/download/CADD/v1.3/{output.file};
		wget http://krishna.gs.washington.edu/download/CADD/v1.3/{output.index};
		"""

rule download_CADD_exon_SNVs:
	output:
		file="cadd_exon_snv.v1.3.tsv.gz",
		index="cadd_exon_snv.v1.3.tsv.gz.tbi"
	shell:
		"""
		wget https://uni-bonn.sciebo.de/s/w0Xn5Fp98apnFFP/download -O {output.file};
		wget https://uni-bonn.sciebo.de/s/f2uEPt4QTg8fqnB/download -O {output.index};
		"""

rule download_CADD_exon_indel:
	output:
		file="cadd_exon_indel.v1.3.tsv.gz",
		index="cadd_exon_indel.v1.3.tsv.gz.tbi"
	shell:
		"""
		wget https://uni-bonn.sciebo.de/s/7mIgAIgKdZeoaRy/download -O {output.file};
		wget https://uni-bonn.sciebo.de/s/ixDVGyqWmvmOxOm/download -O {output.index};
		"""
