subworkflow patho_workflow: 
    workdir: "pathogenicityScores"
    snakefile: "pathogenicityScores/Snakefile"

subworkflow population_workflow: 
    workdir: "populationDBs"
    snakefile: "populationDBs/Snakefile"

subworkflow reference_workflow: 
    workdir: "referenceGenome"
    snakefile: "referenceGenome/Snakefile"

subworkflow jannovar_workflow: 
    workdir: "jannovar"
    snakefile: "jannovar/Snakefile"

subworkflow omim_workflow: 
    workdir: "omim"
    snakefile: "omim/Snakefile"

subworkflow dbsnp_workflow: 
    workdir: "dbSNPs"
    snakefile: "dbSNPs/Snakefile"

# download the data!
rule all:
    input:
        patho_workflow("cadd_snv_exon.tsv.gz"),
        patho_workflow("cadd_snv_exon.tsv.gz.tbi"),
        patho_workflow("cadd_indel_exon.tsv.gz"),
        patho_workflow("cadd_indel_exon.tsv.gz.tbi"),
        population_workflow("ALL.wgs.phase3_shapeit2_mvncall_integrated_v5b.20130502.sites.vcf.gz"),
        population_workflow("ALL.wgs.phase3_shapeit2_mvncall_integrated_v5b.20130502.sites.vcf.gz.tbi"),
        population_workflow("ExAC.r1.sites.vep.vcf.gz"),
        population_workflow("ExAC.r1.sites.vep.vcf.gz.tbi"),
        population_workflow("UK10K_COHORT.20160215.sites.vcf.gz"),
        population_workflow("UK10K_COHORT.20160215.sites.vcf.gz.tbi"),
        reference_workflow("data/hg19.fa"),
        reference_workflow("data/hg19.fa.fai"),
        reference_workflow("data/hg19.fa.dict"),
        reference_workflow("data/human_g1k_v37.fasta"),
        reference_workflow("data/human_g1k_v37.fasta.fai"),
        reference_workflow("data/human_g1k_v37.fasta.dict"),
        jannovar_workflow("data/hg19_refseq.ser"),
        jannovar_workflow("jannovar_0.25/data/hg19_refseq.ser"),
        jannovar_workflow("jannovar_0.26/data/hg19_refseq.ser"),
        omim_workflow("genemap2.txt"),
        omim_workflow("mim2gene.txt"),
        omim_workflow("mim_to_ps.json"),
        omim_workflow("mimTitles.txt"),
        omim_workflow("morbidmap.txt"),
        omim_workflow("omim_deprecated_replacement.json"),
        omim_workflow("phenotypicSeries.txt"),
        dbsnp_workflow("b147/All_20160601.vcf.gz"),
        dbsnp_workflow("b147/All_20160601.vcf.gz.tbi")

